title: Jamie Quigley's Blog
email: jamie@quigley.xyz
description: 
baseurl: ""
url: "https://jamiequigley.com"
twitter_username: Sciencentistguy
github_username: Sciencentistguy

# Build settings
theme:
plugins:
  - jekyll-feed
  - jekyll-katex
